// ✅ FICHIER 3: backend/src/main/resources/application.yml
spring:
  application:
    name: retrouvtout-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/retrouvtout_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:retrouvtout}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    com.retrouvtout: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:8080}

  jwt:
    secret: ${JWT_SECRET:dev-secret-key-for-development-only-not-for-production-use}
    expiration: ${JWT_EXPIRATION:86400000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

  cors:
    allowed-origins: http://localhost:8080,http://localhost:3000,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

  upload:
    dir: ${UPLOAD_DIR:./uploads-dev}
    max-file-size: 10485760
    allowed-extensions: jpg,jpeg,png,gif,webp

  notifications:
    email:
      enabled: false
    sms:
      enabled: false
    push:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: dev

  cache:
    type: simple

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.retrouvtout: DEBUG
    org.springframework.security: DEBUG
