# backend/src/main/resources/application-dev.yml - CORS CORRIGÉ

spring:
  config:
    activate:
      on-profile: dev

  # Configuration base de données MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/retrouvtout_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8mb4&useUnicode=true
    username: retrouvtout
    password: password123
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-test-query: SELECT 1

  # Configuration JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          time_zone: UTC
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    open-in-view: false

  # Configuration cache simple (pas Redis)
  cache:
    type: simple

  # Configuration email désactivée en dev
  mail:
    host: localhost
    port: 1025
    username:
    password:

  # Configuration Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    time-zone: UTC

  # DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Configuration serveur
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# Configuration logging pour debug
logging:
  level:
    root: WARN
    com.retrouvtout: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"

# ✅ CONFIGURATION APPLICATION CORRIGÉE
app:
  frontend:
    url: http://localhost:8080

  jwt:
    secret: dev-secret-key-not-for-production-use-a-longer-and-more-secure-key-for-development-only
    expiration: 86400000
    refresh-expiration: 604800000

  # ✅ CORS CORRIGÉ : Origins spécifiques au lieu de "*" avec credentials
  cors:
    allowed-origins: "http://localhost:8080,http://localhost:3000,http://localhost:5173,http://127.0.0.1:8080,http://127.0.0.1:3000,http://127.0.0.1:5173"
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS,HEAD
    allowed-headers: "*"
    exposed-headers: Authorization,Cache-Control,Content-Type,X-Total-Count,X-Page-Number,X-Page-Size
    allow-credentials: true
    max-age: 3600

  upload:
    dir: ./uploads-dev
    max-file-size: 10485760
    allowed-extensions: jpg,jpeg,png,gif,webp

  notifications:
    email:
      enabled: false
    sms:
      enabled: false
    push:
      enabled: false
