# Configuration conforme au cahier des charges uniquement
# Suppression des fonctionnalités non spécifiées

spring:
  application:
    name: retrouvtout-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Base de données - Section 4.1 (MySQL/PostgreSQL)
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/retrouvtout_dev?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:retrouvtout}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  # Configuration email pour notifications - Section 3.3
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}

  # Upload fichiers (photos) - Section 3.2
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  # Sérialisation JSON
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
    time-zone: UTC

# Configuration serveur - Section 5 (Performance)
server:
  port: ${SERVER_PORT:8081}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,application/javascript,text/css

# Configuration logging
logging:
  level:
    root: INFO
    com.retrouvtout: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}

# Configuration application conforme au cahier des charges
app:
  # Frontend URL
  frontend:
    url: ${FRONTEND_URL:http://localhost:8080}

  # JWT pour authentification - Section 3.1
  jwt:
    secret: ${JWT_SECRET:change-this-in-production-very-long-secret-key}
    expiration: ${JWT_EXPIRATION:86400000} # 24 heures
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 jours

  # CORS - Section 4.1 (Front-end moderne)
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # Upload photos - Section 3.2
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    max-file-size: ${UPLOAD_MAX_FILE_SIZE:10485760} # 10MB
    allowed-extensions: jpg,jpeg,png,gif,webp

  # Notifications - Section 3.3
  notifications:
    email:
      enabled: ${EMAIL_NOTIFICATIONS_ENABLED:true}
      from: ${EMAIL_FROM:noreply@retrouvtout.com}
      from-name: ${EMAIL_FROM_NAME:Retrouv'Tout}
    sms:
      enabled: ${SMS_NOTIFICATIONS_ENABLED:false}
      twilio:
        account-sid: ${TWILIO_ACCOUNT_SID:}
        auth-token: ${TWILIO_AUTH_TOKEN:}
        from-number: ${TWILIO_FROM_NUMBER:}
    push:
      enabled: ${PUSH_NOTIFICATIONS_ENABLED:true}

  # Modération - Section 3.4
  moderation:
    auto-approve: ${AUTO_APPROVE_LISTINGS:true}
    max-listings-per-day: ${MAX_LISTINGS_PER_DAY:10}

  # Sécurité - Section 3.4
  security:
    password:
      min-length: ${PASSWORD_MIN_LENGTH:8}

---
# Configuration développement
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/retrouvtout_dev?useSSL=false&serverTimezone=UTC
    username: retrouvtout
    password: password123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    host: localhost
    port: 1025

logging:
  level:
    com.retrouvtout: DEBUG

app:
  frontend:
    url: http://localhost:8080

  jwt:
    secret: dev-secret-key-not-for-production

  notifications:
    email:
      enabled: false
    sms:
      enabled: false
    push:
      enabled: false

  moderation:
    auto-approve: true

---
# Configuration production
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.retrouvtout: INFO

app:
  frontend:
    url: ${FRONTEND_URL:https://retrouvtout.com}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://retrouvtout.com}

  notifications:
    email:
      enabled: true
    sms:
      enabled: ${SMS_NOTIFICATIONS_ENABLED:true}
    push:
      enabled: true

  moderation:
    auto-approve: false
