# Configuration développement - application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
  
  # Base de données développement MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/retrouvtout_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:retrouvtout}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  # Configuration JPA/Hibernate pour le développement
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  
  # Configuration Flyway pour les migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-suffix: .sql
  
  # Configuration Redis pour le développement (simple cache en mémoire)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Cache simple pour le développement
  cache:
    type: simple
  
  # Configuration email pour le développement (console/MailHog)
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    default-encoding: UTF-8
  
  # Configuration multipart (upload fichiers)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      location: ${java.io.tmpdir}
  
  # DÉSACTIVER OAuth2 pour le développement
  security:
    oauth2:
      client:
        registration: {}
  
  # Configuration Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    time-zone: UTC
  
  # DevTools pour le rechargement automatique
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Configuration logging pour le développement
logging:
  level:
    root: INFO
    com.retrouvtout: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    name: logs/retrouvtout-dev.log
    max-size: 10MB
    max-history: 5

# Configuration Management/Actuator pour le développement
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,configprops,mappings,flyway,liquibase
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    beans:
      enabled: true
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: false

# Configuration OpenAPI/Swagger pour le développement
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
  show-actuator: true

# Configuration application spécifique pour le développement
app:
  # Configuration frontend URL
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  
  # Configuration JWT
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-not-for-production}
    expiration: 86400000 # 24 heures en millisecondes
    refresh-expiration: 604800000 # 7 jours en millisecondes
  
  # Configuration CORS permissive pour le développement
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  
  # Configuration upload pour le développement
  upload:
    dir: ${UPLOAD_DIR:./uploads-dev}
    max-file-size: 10485760 # 10MB
    allowed-extensions: jpg,jpeg,png,gif,webp
  
  # Configuration notifications désactivées pour le développement
  notifications:
    email:
      enabled: ${EMAIL_NOTIFICATIONS_ENABLED:false}
      from: ${EMAIL_FROM:dev@retrouvtout.com}
      from-name: "Retrouv'Tout Dev"
    sms:
      enabled: ${SMS_NOTIFICATIONS_ENABLED:false}
      twilio:
        account-sid: ${TWILIO_ACCOUNT_SID:}
        auth-token: ${TWILIO_AUTH_TOKEN:}
        from-number: ${TWILIO_FROM_NUMBER:}
    push:
      enabled: ${PUSH_NOTIFICATIONS_ENABLED:false}
      vapid-public-key: ${VAPID_PUBLIC_KEY:}
      vapid-private-key: ${VAPID_PRIVATE_KEY:}
  
  # Configuration modération permissive pour le développement
  moderation:
    auto-approve: ${AUTO_APPROVE_LISTINGS:true}
    max-listings-per-day: ${MAX_LISTINGS_PER_DAY:100}
    profanity-filter: ${PROFANITY_FILTER_ENABLED:false}
  
  # Configuration géolocalisation pour le développement
  geocoding:
    enabled: ${GEOCODING_ENABLED:false}
    provider: ${GEOCODING_PROVIDER:nominatim}
    api-key: ${GEOCODING_API_KEY:}

# Configuration serveur pour le développement
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
  compression:
    enabled: true