# Configuration développement sans base de données - application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  # ✅ DÉSACTIVER complètement JPA/Hibernate pour les tests
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

  # Configuration cache simple pour le développement
  cache:
    type: simple

  # Configuration Redis DÉSACTIVÉE
  data:
    redis:
      repositories:
        enabled: false

  # Configuration email pour le développement (console/MailHog)
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    default-encoding: UTF-8

  # Configuration multipart (upload fichiers)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      location: ${java.io.tmpdir}

  # Configuration Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: NON_NULL
    time-zone: UTC

  # DevTools pour le rechargement automatique
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Configuration logging pour le développement
logging:
  level:
    root: INFO
    com.retrouvtout: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    # ✅ Réduire les logs de base de données
    org.hibernate: ERROR
    org.springframework.orm: ERROR
    org.springframework.data: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    name: logs/retrouvtout-dev.log
    max-size: 10MB
    max-history: 5

# Configuration Management/Actuator pour le développement
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,configprops,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    beans:
      enabled: true
    env:
      enabled: true

# Configuration OpenAPI/Swagger pour le développement
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
  show-actuator: true

# Configuration application spécifique pour le développement
app:
  # Configuration frontend URL
  frontend:
    url: http://localhost:8080

  # Configuration JWT
  jwt:
    secret: dev-secret-key-not-for-production-use-a-longer-and-more-secure-key
    expiration: 86400000 # 24 heures en millisecondes
    refresh-expiration: 604800000 # 7 jours en millisecondes

  # Configuration CORS permissive pour le développement
  cors:
    allowed-origins: http://localhost:8080,http://localhost:3000,http://localhost:5173
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

  # Configuration upload pour le développement
  upload:
    dir: ./uploads-dev
    max-file-size: 10485760 # 10MB
    allowed-extensions: jpg,jpeg,png,gif,webp

  # Configuration notifications désactivées pour le développement
  notifications:
    email:
      enabled: false
      from: dev@retrouvtout.com
      from-name: "Retrouv'Tout Dev"
    sms:
      enabled: false
    push:
      enabled: false

  # Configuration modération permissive pour le développement
  moderation:
    auto-approve: true
    max-listings-per-day: 100
    profanity-filter: false

  # Configuration géolocalisation pour le développement
  geocoding:
    enabled: false
    provider: nominatim
    api-key:

# Configuration serveur pour le développement
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true
  compression:
    enabled: true
